# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: poplarday
description: >- # this means to ignore newlines until "baseurl:"
  a simple blog
baseurl: "/bay" # the subpath of the site
url: "https://poplarday.github.io" # the base hostname & protocol for the site
og_image: /assets/img/profile-pic.jpg
google_analytics: "UA-121636368-3"

header:
  pages:
    - name: Home
      slug: /
 # - name: Work
    - name: Blog

footer:
  contact:
    - name: Email
      value: poplarday@hotmail.com
      link: poplarday@hotmail.com
    - name: WeChat
      value: ArcCicle
      link: "#"
  follow:
    - name: GitHub
      link: http://github.com/poplarday
    - name: RSS
      link: /feed.xml

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  
# Used for defeating caching
version: 1
