# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: polar
description: >- # this means to ignore newlines until "baseurl:"
  A simple blog
baseurl: "/bay" # the subpath of the site
url: "https://polarcue.github.io" # the base hostname & protocol for the site
og_image: /assets/img/profile-pic.jpg
google_analytics: "UA-121636368-3"

header:
  pages:
    - name: Home
      slug: /
    - name: Blog

footer:
  show_powered_by: false
  contact:
    - type: email
      name: waner@ik.me
      value: waner@ik.me
    - type: wechat
      value: ArcCircle
      link: "#"
  follow:
    - type: bilibili
      name: Bilibili
      link: https://space.bilibili.com/481155413

# Build settings
markdown: kramdown
kramdown:
  math_engine: null
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
